disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - line_length
  - force_cast
  - force_try
  - function_body_length
  - type_body_length
  - file_length
  - cyclomatic_complexity
  - large_tuple

opt_in_rules: # some rules are only opt-in
  - empty_count
  - closure_spacing
  - fatal_error_message
  - first_where
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - private_action
  - private_outlet
  - prohibited_super_call
  - sorted_imports

included: # paths to include during linting. `--path` is ignored if present.
  - InOfficeDaysTracker
  - OfficeTrackerWidget

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - DerivedData
  - build
  - fastlane
  - docs

# configuration parameters
line_length: 120
identifier_name:
  min_length: 3 # only warning
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
